src/components/Footer.tsx

Add component Footer

---

src/components/Hero/Background.tsx
src/components/Hero/index.tsx
src/index.css

Fix background gradient

---

src/components/Ticket.tsx
src/index.css

Before:
https://github.com/Afordin/hackafor-2/assets/62910118/01c20a25-ffab-47d7-bb86-e463edc73bec
After: 
https://github.com/Afordin/hackafor-2/assets/62910118/7325ea0f-d43a-4c53-b238-db94fe839f2a

improve ticket UI

---

README.md
src/components/CTA.tsx
src/components/Hero/Background.tsx
src/components/Hero/index.tsx
uno.config.ts

- Fix bug in font weight  
https://github.com/Afordin/hackafor-2/issues/20
- Add images to readme
- Remove Remove h-[100vh]

Fix bug with DM Sans weights & update readme

---

src/components/Background/Background.tsx
src/components/Footer/Footer.tsx
src/pages/Home.tsx
src/pages/_sections/CTA.tsx
src/pages/_sections/Hero.tsx
src/pages/_sections/Information.tsx
src/pages/_sections/Ticket.tsx

- Reduce margin between hero and information 
- Reduce vanta animation size and remove absolute height
- Fix overlapping btw item 
- Add className prop to the CTA component
- Fix square border in the ticket
Before:
After:

Improve UI

---

src/components/Background/Background.tsx

Modified the animation colors to avoid colors like white and golden

Modified default vanta colors

---

vercel.json

Se añade configuración Vercel (`vercel.json`) para sobrescribir routing
- https://github.com/Afordin/hackafor-2/issues/33

Add Vercel config to rewrites routing

---

README.md

Add: contributing to a project

---

src/pages/_sections/CTA.tsx
src/pages/_sections/Hero.tsx

feat: Implement responsive design for homepage section

---

src/common/hooks/index.ts
src/common/hooks/useContributors/useContributors.ts
src/common/index.ts
src/common/types/general.ts
src/common/types/index.ts
src/components/Footer/Footer.tsx
src/components/Navigation/Nav.tsx
src/index.css

En este pull request, se han aplicado mejoras significativas y re-factorizaciones tanto en los componentes `Nav` como en Footer de nuestro proyecto. Al integrar el `hook` `useContributors`, hemos abstraído la lógica de `fetch` asíncrono fuera de los componentes, lo que lleva a un código más limpio y mantenible. La introducción de la función `cn` para la gestión de nombres de clase en el componente Footer enfatiza aún más nuestro compromiso con una arquitectura CSS mantenible y escalable dentro de los componentes React.
Notablemente, el componente Footer ha sufrido una re-factorización que no solo mejoró su estructura sino también sus características de accesibilidad, asegurando una mejor experiencia de usuario para todos los usuarios, incluidos aquellos que dependen de tecnologías de …

Feature / Improve footer and general accessibility

---

src/pages/_sections/CTA.tsx
src/pages/_sections/Hero.tsx
src/pages/_sections/Ticket.tsx

I added a responsive ticket for the main page in order to resolve the issue #39 
Before: 
Large mobiles:
Small mobiles:
Now: 
Large mobiles: 
Small mobiles:

Ticket responsive

---

package.json
pnpm-lock.yaml
src/common/constants/breakpoints.ts
src/common/constants/index.ts
src/common/hooks/index.ts
src/common/hooks/useBreakpoint/useBreakpoint.ts
src/common/hooks/useWindowSize/useWindowSize.ts
src/common/utils/index.ts
src/common/utils/setIconByPreferenceScheme.ts
src/common/utils/utils.ts
src/components/Buttons/Button/Button.tsx
src/components/Navigation/Nav.tsx
src/index.css
src/main.tsx
src/pages/_sections/CTA.tsx
src/pages/_sections/FeatureProjects.tsx
src/pages/_sections/Ticket.tsx
uno.config.ts

En esta actualización, se han realizado mejoras y adiciones significativas para mejorar la funcionalidad y experiencia del usuario en el proyecto:
1. **Colores Primarios y Secundarios Añadidos**: Se han introducido colores primarios y secundarios personalizados en `uno.config.ts` para refinar la apariencia de la interfaz de usuario, haciéndola más atractiva y consistente.
2. **Nuevos Hooks para Diseño Responsivo**: Se añadieron los hooks `useBreakpoint` y `useWindowSize`. Estos hooks facilitan el diseño responsivo permitiendo que los componentes se adapten en función del tamaño de la ventana de visualización.
3. **Adición de Dependencia**: Se agregó `lodash.throttle` para mejorar el rendimiento de los cálculos basados en el tamaño de la ventana, asegurando una experiencia de usuario más …

Feature / Improve colors and minor changes

---

src/components/Navigation/Nav.tsx

Agregar color diferenciador a la página activa

Add identifier in active page

---

src/components/Navigation/Nav.tsx

Remove listItemActive class from nav classes
suggestion from @Zyruks

Refactor Nav

---

src/components/Navigation/Nav.tsx
src/pages/_sections/FeatureProjects.tsx
src/pages/_sections/Ticket.tsx

Accessibility Update: Improved Contrast and Heading Structure

---

README.md

afor adoptame

---

.github/PULL_REQUEST_TEMPLATE.md
.husky/commit-msg
.husky/pre-commit
commitlint.config.mjs
lint-staged.config.mjs
package.json
pnpm-lock.yaml
src/components/Buttons/BurgerButton/BurgerButton.tsx

Se han realizado configuraciones clave para mejorar el proceso de desarrollo y contribución al proyecto:
- Se introdujo `lint-staged.config.mjs` para automatizar el formateo y linting de código antes de cada commit, asegurando la calidad del código y consistencia en el estilo.
- Se configuró `commitlint` mediante `commitlint.config.mjs`, utilizando la convención estándar para garantizar que todos los mensajes de commit sigan un formato uniforme y descriptivo.
- Se actualizó el hook de `commit-msg` de husky para integrar `commitlint`, promoviendo buenas prácticas en las contribuciones.
- Se añadió una plantilla de Pull Request en `.github/PULL_REQUEST_TEMPLATE.md` para estandarizar la información requerida en las contribuciones, facilitando la revisión de cambios y asegurando que se …

Feature / Code quality updates

---

src/index.css
src/pages/Home.tsx
src/pages/_sections/CTA.tsx
src/pages/_sections/Hero.tsx
uno.config.ts

Se han implementado varias mejoras en los componentes `Hero`, `CTA` y `Home` para enriquecer la experiencia del usuario y optimizar la legibilidad del código:
- **Hero**: Introducción de tamaños de fuente fluidos y ajustes de colores de tema para una mayor responsividad y consistencia visual.
- **CTA**: Mejora en la adaptabilidad y estilización del componente, incluyendo tipografías fluidas y ajustes de tamaño de botón basados en el breakpoint del dispositivo.
- **Home**: Ajuste menor al centrar el texto dentro del componente `CTA` para mejorar la alineación visual y cohesión en el diseño de la página principal.
Estos cambios buscan proporcionar una interfaz más dinámica, accesible y agradable para los usuarios, adaptándose mejor a diferentes tamaños de pantalla y preferencias de …

Feature / Improve hero responsive text

---

src/components/Cards/SimpleCard/SimpleCard.tsx
src/pages/_sections/Information.tsx

Se han implementado ajustes de estilo y diseño en la componente Information y en el uso de SimpleCard para mejorar la experiencia de usuario y la responsividad. Se introdujeron cambios específicos como:
- Ajuste del tamaño de las imágenes para un diseño más responsivo.
- Transición de un diseño basado en flex a uno basado en grid para las tarjetas de información, mejorando la uniformidad en diferentes tamaños de pantalla.
- Mejora de la responsividad de las imágenes con clases de utilidad de altura y ancho completos.
- Implementación de estilos personalizados mediante props `className` y `innerContainerClassName` en SimpleCards para un control más detallado del diseño y la tipografía.
- Se ha agregado un comentario detallado explicando el uso temporal de `!important` para sobrescribir el …

Feature / Improve responsive information section

---

src/common/constants/index.ts
src/common/constants/tag.ts
src/components/Tag/Tag.tsx
src/components/index.ts

Este PR introduce el componente `Tag`, una nueva adición a nuestra biblioteca de componentes UI que permite a los usuarios visualizar etiquetas con variantes y tamaños personalizables. Esta característica está diseñada para mejorar la flexibilidad y la coherencia en la visualización de etiquetas a través de nuestra aplicación.
El componente `Tag` soporta las siguientes propiedades:
- `variant`: Define el estilo visual del tag (por ejemplo, `primary`, `secondary`, `neutral`).
- `size`: Establece el tamaño del tag (por ejemplo, `xs`, `sm`, `md`, `lg`).
- `borderSize`: Controla el grosor del borde del tag.
Además, se han definido `Enums` `TagVariant` y `TagSize` en `common/constants/tags.ts` para estandarizar las opciones disponibles para los usuarios del componente.

Feature / Tag Component

---

src/components/TwitchLive/TwitchLive.tsx
src/components/index.ts
src/pages/_sections/Hero.tsx

Add Twitch Live Button 

---

src/common/hooks/useContributors/useContributors.ts

fix: sort contributors by contributions

---

src/index.css

Se ha modificado el estilo del scroll para mejorar la estética y la usabilidad de la aplicación.
- N/A
Antes:
https://github.com/Afordin/hackafor-2/assets/67854304/0fc4ad5e-4688-4328-a9e5-91339de11705
Despues:
https://github.com/Afordin/hackafor-2/assets/67854304/d14a8fc3-fa80-4ee2-b72a-a6a2164a165f

feat(scroll): add custom styles to scrollbar

---

src/index.css

- Numero de Issue
**Before**
**After**

fix: padding in contributors container

---

package.json
pnpm-lock.yaml
src/pages/_sections/Ticket.tsx

Implementación de botones para Compartir y Descargar:
Este PR introduce dos nuevas características a la funcionalidad del proyecto:
1. **Botón Compartir en Twitter**: Permite a los usuarios registrados compartir su Ticket directamente en Twitter. (Falta integrar con Vercel Functions y Supabase)
2. **Botón Descargar**: Ofrece a los usuarios la posibilidad de descargar el Ticket.
Estos incluye también el uso de la librería [html-to-image](https://www.npmjs.com/package/html-to-image) para la generación de imagenes.
Pendiente:
- El diseño de los botónes debería cambiar para que vaya mas de acuerdo con los diseños originalmente propuestos.
- La funcionalidad completa requiere la integración con Supabase, la cual se encuentra en desarrollo y se implementará en un PR posterior.
- [Make download …

feat: add ticket sharing buttons and functionality

---

README.md

Se cambió el npm a pnpm en el readme

docs(README): :memo: update from npm to pnpm

---

src/components/Footer/Footer.tsx
src/index.css

Adding anchor to "Ana Rangel" and "aforcita" and add hover to those anchors
https://github.com/Afordin/hackafor-2/assets/161905693/360c7d86-2bcb-478c-a8b5-9b4711aaab04

Feature / Add Hover State to footer anchor links

---

src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.tsx
src/components/Buttons/index.ts
src/pages/Projects/Projects.tsx

Se ha integrado el componente `ToggleButtonGroup` en el componente `Projects` para gestionar de manera eficiente los estados activo/inactivo de los proyectos. Esto simplifica la gestión de estados utilizando un único hook `isActive` en lugar del anterior enum `PROJECT_PAGE_STATUS`, lo que mejora la legibilidad del código y reduce la complejidad. Se eliminó el enum `PROJECT_PAGE_STATUS` que ya no se utiliza y se ajustó la lógica para mostrar proyectos activos o cerrados basados en el nuevo estado `isActive`. Este refactor mejora la estructura interna y la legibilidad del componente `Projects`, además de aprovechar la reusabilidad del componente `ToggleButtonGroup`, optimizando el código de la interfaz de usuario.
https://github.com/Afordin/hackafor-2/assets/14036522/75e828b3-fe28-4f25-9517- …

Feature / Add toggle button group component

---

src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.tsx
src/components/Cards/CardWrapper/CardWrapper.tsx
src/components/Cards/ProjectCard/ProjectCard.tsx
src/components/Cards/index.ts
src/components/Tag/Tag.tsx
src/index.css
src/pages/Projects/Projects.tsx
src/pages/Projects/types.ts

- **Extensión de Componentes**: Los componentes `CardWrapper` y `ProjectCard` ahora aceptan todos los `HTMLAttributes<HTMLDivElement>`. Esta mejora añade una gran flexibilidad y permite una personalización más profunda mediante la aceptación de atributos HTML estándar como `style`, `id`, o atributos `data-*`. 
- **Animación Personalizada**: Implementamos una animación de fade-up personalizada `.animate-fade-up-custom` para mejorar la transición visual de elementos. Esta animación contribuye a una experiencia de usuario más dinámica y atractiva, especialmente útil en la presentación de `ProjectCard`.
- **Página de Projects - Refinamientos Clave**:
- **Integración de ProjectCard**: La visualización de proyectos ahora utiliza el componente `ProjectCard` para una representación unificada y …

Feature: Add project cards

---

src/components/Countdown/Countdown.tsx
src/components/index.ts
src/pages/_sections/Information.tsx

https://github.com/Afordin/hackafor-2/assets/110699874/18a7c91c-e4cd-4a96-a794-a022fa7277e2
The day that is counting down is November 20

Add a countdown to Hackafor day

---

src/components/Countdown/Countdown.tsx

Center hours in the countdown component

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-failing-test.yml
.github/ISSUE_TEMPLATE/3-docs-bug.yml
.github/ISSUE_TEMPLATE/4-feature-request.yml
.github/ISSUE_TEMPLATE/5-enhancement-request.yml
.github/ISSUE_TEMPLATE/6-security-report.yml
.github/ISSUE_TEMPLATE/7-question-support.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/labels.yml
.github/workflows/ci.yml
.github/workflows/commitlint.yml
.github/workflows/labels.yml
docs/CODE_OF_CONDUCT.md

- Se agrega nuevas funcionalidades de CI/CD
- Se agregaron los templates para ISSUES
- Se agregaron los label updaters
- se agrego commitlint CI
- Se agrego el codigo de conducta generico

docs(pr-template): 📝 update pr template from spanish to english

---

src/components/Footer/Footer.tsx

change twitter hover and change Developed by Comuafor

---

src/components/Footer/Footer.tsx

feat: fix footer

---

src/components/Countdown/Countdown.tsx
src/pages/_sections/Hero.tsx

fix: make the countdown responsive
Instead of it being a grid it is a single line
Before:
After:

Count down responsive

---

index.html

https://www.youtube.com/watch?v=jK7IPbnmvVU
- [ X ] fix: corrected a bug with login functionality
Removed unused meta keywords. It has been unused for more than 14 years.
- [ X  ] My code follows the code style of this project.

fix: remove unused meta keyword

---

src/components/Footer/Footer.tsx

update html entity from "ensp" to "nbsp"
- Issue Number
Before:
After:

style(components/footer): update html entities

---

src/components/Navigation/LoggedUser.tsx
src/components/Navigation/Nav.tsx

Add modal to logout and improve mobile design

---

src/components/Background/Background.tsx

Add brightness filter to improve the constrast between the animated background and the main title.
- Issue Number
https://github.com/Afordin/hackafor-2/assets/53484686/6bf937a0-37aa-4adc-af2c-ca5bd130b556

feat: add brightness filter to vanta background

---

.env.example
src/pages/_sections/Ticket.tsx

feat: update .env.example and ticket component to use VITE_WEBSITE_URL

---

src/pages/_sections/Ticket.tsx

Completed Twitter image sharing by resizing the image before generating the png. This helps with how the image looks on Twitter.

feat: add img resizing for generation and twitter share message

---

src/components/Countdown/Countdown.tsx
src/pages/_sections/FeatureProjects.tsx

@afordigital The Hackafor Supabase's project is paused
- Issue Number

update countdown date & prevent rendering of FeatureProjects when no projects are available
